service:
  storage:
    embedded:
      flyway:
        enabled: 'true'
        encoding: 'UTF-8'
        schema: STORAGE_SERVICE
        locations: classpath:/embedded/storage/db/migration
        default-schema: STORAGE_SERVICE
        schemas: STORAGE_SERVICE
        placeholders:
          schema: STORAGE_SERVICE
      folder: data
      buffer-size: '1024'
      storage-format: GZIP
      default-storage-container: FILE